apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echelon
  annotations:
    run.googleapis.com/client-name: echelon-google-ads
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/echelon:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: ENV
          value: "production"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        secret:
          secretName: echelon-google-ads-config 